#!/usr/bin/env python3
from __future__ import annotations

import json
import os
import subprocess
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
LOG_DIR = ROOT / "docs" / "experiments" / "track-c"
STATE_PATH = LOG_DIR / "autoresearch-state.json"
STATUS_PATH = LOG_DIR / "autoresearch-status.md"
LOOP_LOG = LOG_DIR / "autoresearch-loop.log"
MAX_PARALLEL = int(os.environ.get("TRACK_C_MAX_PARALLEL", "10"))
COMMIT = os.environ.get("FLIPBOOK_COMMIT", "dirty")


BASE_ARGS = [
    "--steps",
    "4500",
    "--train-resolution",
    "1280x736",
    "--edge-sample-ratio",
    "0.1",
    "--edge-loss-weight",
    "1.0",
    "--text-box-sample-ratio",
    "0.55",
    "--text-box-loss-weight",
    "8.0",
    "--text-box-padding",
    "4",
    "--text-box-min-conf",
    "55",
]

GENERAL_VISUAL_ARGS = [
    "--steps",
    "4500",
    "--train-resolution",
    "1280x736",
    "--text-box-sample-ratio",
    "0",
    "--text-box-loss-weight",
    "0",
    "--text-box-padding",
    "0",
    "--text-box-min-conf",
    "55",
]


def general_visual_motion_args(
    label: str,
    *,
    steps: int = 4500,
    seed: int = 0,
    flow: float = 0.014,
    edge_ratio: float = 0.1,
    edge_weight: float = 1.0,
    motion_mode: str = "jiggle",
    motion_strength: float | None = None,
    video_viewport_mode: str = "static",
    viewport_zoom: float = 0.0,
    viewport_pan: float = 0.0,
    video_layout_mode: str = "none",
    layout_transform_strength: float = 0.0,
    layout_transform_pan: float = 0.0,
    min_ocr: float = 0.78,
    min_motion: float = 0.014,
) -> list[str]:
    base_args = [*GENERAL_VISUAL_ARGS]
    base_args[base_args.index("--steps") + 1] = str(steps)
    args = [
        *base_args,
        "--seed",
        str(seed),
        "--edge-sample-ratio",
        f"{edge_ratio:g}",
        "--edge-loss-weight",
        f"{edge_weight:g}",
        "--flow-scale",
        f"{flow:g}",
        "--motion-mode",
        motion_mode,
        "--motion-strength",
        f"{(flow if motion_strength is None else motion_strength):g}",
        "--experiment-label",
        label,
        "--min-ocr-similarity",
        f"{min_ocr:g}",
        "--min-motion-delta",
        f"{min_motion:g}",
    ]
    if video_viewport_mode != "static":
        args.extend(
            [
                "--video-viewport-mode",
                video_viewport_mode,
                "--viewport-zoom",
                f"{viewport_zoom:g}",
                "--viewport-pan",
                f"{viewport_pan:g}",
            ]
        )
    if video_layout_mode != "none":
        args.extend(
            [
                "--video-layout-mode",
                video_layout_mode,
                "--layout-transform-strength",
                f"{layout_transform_strength:g}",
                "--layout-transform-pan",
                f"{layout_transform_pan:g}",
            ]
        )
    return args


@dataclass(frozen=True)
class Experiment:
    label: str
    args: list[str]
    notes: str

    @property
    def session(self) -> str:
        return f"track-c-{self.label}"

    @property
    def log_path(self) -> Path:
        return LOG_DIR / f"{self.label}.log"


EXPERIMENTS = [
    Experiment(
        label="c37-frame-scale-012-edge09-s6000",
        notes="C37 resize refinement: repeat the best C35 0.12/edge09 bracket with more optimization steps.",
        args=general_visual_motion_args(
            "c37-frame-scale-012-edge09-s6000",
            steps=6000,
            edge_ratio=0.09,
            edge_weight=0.9,
            motion_mode="static",
            motion_strength=0.0,
            video_layout_mode="frame-scale",
            layout_transform_strength=0.12,
            layout_transform_pan=0.024,
            min_ocr=0.60,
            min_motion=0.04,
        ),
    ),
    Experiment(
        label="c37-frame-scale-0125-edge09",
        notes="C37 resize refinement: locate the cliff just above the C35 0.12 pass.",
        args=general_visual_motion_args(
            "c37-frame-scale-0125-edge09",
            edge_ratio=0.09,
            edge_weight=0.9,
            motion_mode="static",
            motion_strength=0.0,
            video_layout_mode="frame-scale",
            layout_transform_strength=0.125,
            layout_transform_pan=0.024,
            min_ocr=0.58,
            min_motion=0.04,
        ),
    ),
    Experiment(
        label="c37-frame-scale-013-edge09",
        notes="C37 resize refinement: mid-point between C35 0.12 and C36 0.14.",
        args=general_visual_motion_args(
            "c37-frame-scale-013-edge09",
            edge_ratio=0.09,
            edge_weight=0.9,
            motion_mode="static",
            motion_strength=0.0,
            video_layout_mode="frame-scale",
            layout_transform_strength=0.13,
            layout_transform_pan=0.025,
            min_ocr=0.56,
            min_motion=0.04,
        ),
    ),
    Experiment(
        label="c37-frame-scale-0135-edge09",
        notes="C37 resize refinement: upper mid-point before the C36 0.14 quality drop.",
        args=general_visual_motion_args(
            "c37-frame-scale-0135-edge09",
            edge_ratio=0.09,
            edge_weight=0.9,
            motion_mode="static",
            motion_strength=0.0,
            video_layout_mode="frame-scale",
            layout_transform_strength=0.135,
            layout_transform_pan=0.026,
            min_ocr=0.54,
            min_motion=0.04,
        ),
    ),
    Experiment(
        label="c37-frame-scale-014-edge09-s6000",
        notes="C37 resize refinement: test whether more steps rescue the C36 0.14/edge09 setting.",
        args=general_visual_motion_args(
            "c37-frame-scale-014-edge09-s6000",
            steps=6000,
            edge_ratio=0.09,
            edge_weight=0.9,
            motion_mode="static",
            motion_strength=0.0,
            video_layout_mode="frame-scale",
            layout_transform_strength=0.14,
            layout_transform_pan=0.027,
            min_ocr=0.55,
            min_motion=0.04,
        ),
    ),
    Experiment(
        label="c37-frame-scale-014-edge075-s6000",
        notes="C37 resize refinement: more steps on the lighter-edge 0.14 bracket.",
        args=general_visual_motion_args(
            "c37-frame-scale-014-edge075-s6000",
            steps=6000,
            edge_ratio=0.075,
            edge_weight=0.75,
            motion_mode="static",
            motion_strength=0.0,
            video_layout_mode="frame-scale",
            layout_transform_strength=0.14,
            layout_transform_pan=0.027,
            min_ocr=0.53,
            min_motion=0.04,
        ),
    ),
    Experiment(
        label="c37-frame-scale-016-edge075-s6000",
        notes="C37 resize refinement: check whether the 0.16 strong-resize pass improves with more steps.",
        args=general_visual_motion_args(
            "c37-frame-scale-016-edge075-s6000",
            steps=6000,
            edge_ratio=0.075,
            edge_weight=0.75,
            motion_mode="static",
            motion_strength=0.0,
            video_layout_mode="frame-scale",
            layout_transform_strength=0.16,
            layout_transform_pan=0.030,
            min_ocr=0.44,
            min_motion=0.04,
        ),
    ),
    Experiment(
        label="c37-frame-scale-014-edge09-pan000",
        notes="C37 resize isolation: remove pan at 0.14/edge09 to separate scaling from repositioning.",
        args=general_visual_motion_args(
            "c37-frame-scale-014-edge09-pan000",
            edge_ratio=0.09,
            edge_weight=0.9,
            motion_mode="static",
            motion_strength=0.0,
            video_layout_mode="frame-scale",
            layout_transform_strength=0.14,
            layout_transform_pan=0.0,
            min_ocr=0.56,
            min_motion=0.04,
        ),
    ),
    Experiment(
        label="c37-frame-scale-014-edge09-pan018",
        notes="C37 resize isolation: reduced pan at 0.14/edge09 to quantify scale-plus-reposition cost.",
        args=general_visual_motion_args(
            "c37-frame-scale-014-edge09-pan018",
            edge_ratio=0.09,
            edge_weight=0.9,
            motion_mode="static",
            motion_strength=0.0,
            video_layout_mode="frame-scale",
            layout_transform_strength=0.14,
            layout_transform_pan=0.018,
            min_ocr=0.55,
            min_motion=0.04,
        ),
    ),
    Experiment(
        label="c37-frame-scale-014-edge075-pan000",
        notes="C37 resize isolation: no-pan version of the lighter-edge 0.14 bracket.",
        args=general_visual_motion_args(
            "c37-frame-scale-014-edge075-pan000",
            edge_ratio=0.075,
            edge_weight=0.75,
            motion_mode="static",
            motion_strength=0.0,
            video_layout_mode="frame-scale",
            layout_transform_strength=0.14,
            layout_transform_pan=0.0,
            min_ocr=0.54,
            min_motion=0.04,
        ),
    ),
    Experiment(
        label="c36-frame-scale-014-edge075",
        notes="C36 resize cliff: frame-scale 0.14 with lighter edge weighting, no OCR boxes.",
        args=general_visual_motion_args(
            "c36-frame-scale-014-edge075",
            edge_ratio=0.075,
            edge_weight=0.75,
            motion_mode="static",
            motion_strength=0.0,
            video_layout_mode="frame-scale",
            layout_transform_strength=0.14,
            layout_transform_pan=0.027,
            min_ocr=0.48,
            min_motion=0.04,
        ),
    ),
    Experiment(
        label="c36-frame-scale-014-edge09",
        notes="C36 resize cliff: frame-scale 0.14 at the better C35 edge09 setting.",
        args=general_visual_motion_args(
            "c36-frame-scale-014-edge09",
            edge_ratio=0.09,
            edge_weight=0.9,
            motion_mode="static",
            motion_strength=0.0,
            video_layout_mode="frame-scale",
            layout_transform_strength=0.14,
            layout_transform_pan=0.027,
            min_ocr=0.50,
            min_motion=0.04,
        ),
    ),
    Experiment(
        label="c36-frame-scale-014-edge1",
        notes="C36 resize cliff: frame-scale 0.14 at edge1 to locate the degradation slope.",
        args=general_visual_motion_args(
            "c36-frame-scale-014-edge1",
            motion_mode="static",
            motion_strength=0.0,
            video_layout_mode="frame-scale",
            layout_transform_strength=0.14,
            layout_transform_pan=0.027,
            min_ocr=0.48,
            min_motion=0.04,
        ),
    ),
    Experiment(
        label="c36-frame-scale-016-edge075",
        notes="C36 strong resize: test whether lighter edge weighting rescues the C35 0.16 near-miss.",
        args=general_visual_motion_args(
            "c36-frame-scale-016-edge075",
            edge_ratio=0.075,
            edge_weight=0.75,
            motion_mode="static",
            motion_strength=0.0,
            video_layout_mode="frame-scale",
            layout_transform_strength=0.16,
            layout_transform_pan=0.030,
            min_ocr=0.42,
            min_motion=0.04,
        ),
    ),
    Experiment(
        label="c36-frame-scale-016-edge09",
        notes="C36 strong resize: edge09 version of the 0.16 resize stress.",
        args=general_visual_motion_args(
            "c36-frame-scale-016-edge09",
            edge_ratio=0.09,
            edge_weight=0.9,
            motion_mode="static",
            motion_strength=0.0,
            video_layout_mode="frame-scale",
            layout_transform_strength=0.16,
            layout_transform_pan=0.030,
            min_ocr=0.42,
            min_motion=0.04,
        ),
    ),
    Experiment(
        label="c36-frame-scale-016-edge09-s6000",
        notes="C36 strong resize: more optimization steps at the best likely 0.16 edge bracket.",
        args=general_visual_motion_args(
            "c36-frame-scale-016-edge09-s6000",
            steps=6000,
            edge_ratio=0.09,
            edge_weight=0.9,
            motion_mode="static",
            motion_strength=0.0,
            video_layout_mode="frame-scale",
            layout_transform_strength=0.16,
            layout_transform_pan=0.030,
            min_ocr=0.44,
            min_motion=0.04,
        ),
    ),
    Experiment(
        label="c36-frame-scale-018-edge075",
        notes="C36 over-stress: frame-scale 0.18 with lighter edge weighting to find the hard failure point.",
        args=general_visual_motion_args(
            "c36-frame-scale-018-edge075",
            edge_ratio=0.075,
            edge_weight=0.75,
            motion_mode="static",
            motion_strength=0.0,
            video_layout_mode="frame-scale",
            layout_transform_strength=0.18,
            layout_transform_pan=0.034,
            min_ocr=0.35,
            min_motion=0.04,
        ),
    ),
    Experiment(
        label="c36-frame-scale-018-edge05",
        notes="C36 over-stress: frame-scale 0.18 with very light edge weighting.",
        args=general_visual_motion_args(
            "c36-frame-scale-018-edge05",
            edge_ratio=0.05,
            edge_weight=0.5,
            motion_mode="static",
            motion_strength=0.0,
            video_layout_mode="frame-scale",
            layout_transform_strength=0.18,
            layout_transform_pan=0.034,
            min_ocr=0.35,
            min_motion=0.04,
        ),
    ),
    Experiment(
        label="c36-learned-frame-scale-006-flow04",
        notes="C36 learned resize: train the neural renderer itself on mild frame-scale motion, no layout transform.",
        args=general_visual_motion_args(
            "c36-learned-frame-scale-006-flow04",
            flow=0.04,
            motion_mode="frame-scale",
            motion_strength=0.06,
            min_ocr=0.48,
            min_motion=0.04,
        ),
    ),
    Experiment(
        label="c36-learned-frame-scale-008-flow05",
        notes="C36 learned resize: stronger learned frame-scale motion with higher flow budget.",
        args=general_visual_motion_args(
            "c36-learned-frame-scale-008-flow05",
            flow=0.05,
            motion_mode="frame-scale",
            motion_strength=0.08,
            min_ocr=0.42,
            min_motion=0.04,
        ),
    ),
    Experiment(
        label="c35-viewport-014-edge1-z006",
        notes="C35 aggressive viewport stress: no-OCR winner under zoom-pulse viewport movement.",
        args=general_visual_motion_args(
            "c35-viewport-014-edge1-z006",
            video_viewport_mode="zoom-pulse",
            viewport_zoom=0.06,
            viewport_pan=0.012,
            min_ocr=0.78,
            min_motion=0.02,
        ),
    ),
    Experiment(
        label="c35-viewport-014-edge1-z010",
        notes="C35 aggressive viewport stress: larger zoom/pan, still no OCR boxes or masks.",
        args=general_visual_motion_args(
            "c35-viewport-014-edge1-z010",
            video_viewport_mode="zoom-pulse",
            viewport_zoom=0.10,
            viewport_pan=0.018,
            min_ocr=0.74,
            min_motion=0.025,
        ),
    ),
    Experiment(
        label="c35-viewport-014-edge1-z014",
        notes="C35 aggressive viewport stress: high zoom/pan to find query-stability failure modes.",
        args=general_visual_motion_args(
            "c35-viewport-014-edge1-z014",
            video_viewport_mode="zoom-pulse",
            viewport_zoom=0.14,
            viewport_pan=0.024,
            min_ocr=0.70,
            min_motion=0.03,
        ),
    ),
    Experiment(
        label="c35-frame-scale-008-edge1",
        notes="C35 resize stress: global frame-scale layout transform with no OCR boxes.",
        args=general_visual_motion_args(
            "c35-frame-scale-008-edge1",
            motion_mode="static",
            motion_strength=0.0,
            video_layout_mode="frame-scale",
            layout_transform_strength=0.08,
            layout_transform_pan=0.018,
            min_ocr=0.62,
            min_motion=0.04,
        ),
    ),
    Experiment(
        label="c35-frame-scale-012-edge1",
        notes="C35 resize stress: stronger global frame-scale layout transform with no OCR boxes.",
        args=general_visual_motion_args(
            "c35-frame-scale-012-edge1",
            motion_mode="static",
            motion_strength=0.0,
            video_layout_mode="frame-scale",
            layout_transform_strength=0.12,
            layout_transform_pan=0.024,
            min_ocr=0.52,
            min_motion=0.04,
        ),
    ),
    Experiment(
        label="c35-frame-scale-016-edge1",
        notes="C35 resize stress: strong global frame-scale layout transform to expose text repainting.",
        args=general_visual_motion_args(
            "c35-frame-scale-016-edge1",
            motion_mode="static",
            motion_strength=0.0,
            video_layout_mode="frame-scale",
            layout_transform_strength=0.16,
            layout_transform_pan=0.030,
            min_ocr=0.42,
            min_motion=0.04,
        ),
    ),
    Experiment(
        label="c35-responsive-014-edge1-z006",
        notes="C35 combined stress: responsive-squeeze plus viewport zoom, no OCR boxes.",
        args=general_visual_motion_args(
            "c35-responsive-014-edge1-z006",
            motion_mode="responsive-squeeze",
            video_viewport_mode="zoom-pulse",
            viewport_zoom=0.06,
            viewport_pan=0.012,
            min_ocr=0.78,
            min_motion=0.02,
        ),
    ),
    Experiment(
        label="c35-responsive-016-edge1-z008",
        notes="C35 combined stress: stronger responsive-squeeze plus viewport zoom.",
        args=general_visual_motion_args(
            "c35-responsive-016-edge1-z008",
            flow=0.016,
            motion_mode="responsive-squeeze",
            video_viewport_mode="zoom-pulse",
            viewport_zoom=0.08,
            viewport_pan=0.016,
            min_ocr=0.70,
            min_motion=0.025,
        ),
    ),
    Experiment(
        label="c35-frame-scale-012-edge09",
        notes="C35 resize bracket: frame-scale with slightly lighter edge weighting.",
        args=general_visual_motion_args(
            "c35-frame-scale-012-edge09",
            edge_ratio=0.09,
            edge_weight=0.9,
            motion_mode="static",
            motion_strength=0.0,
            video_layout_mode="frame-scale",
            layout_transform_strength=0.12,
            layout_transform_pan=0.024,
            min_ocr=0.52,
            min_motion=0.04,
        ),
    ),
    Experiment(
        label="c35-control-wiggle-014-edge1",
        notes="C35 control only: one local-motion repeat so aggressive tests can be compared to the known winner.",
        args=general_visual_motion_args(
            "c35-control-wiggle-014-edge1",
            min_ocr=0.84,
        ),
    ),
    Experiment(
        label="c34-general-flow-014-edge1-seed0",
        notes="C34 robustness: repeat the C33 no-OCR winner with explicit deterministic seed 0.",
        args=[
            *GENERAL_VISUAL_ARGS,
            "--seed",
            "0",
            "--edge-sample-ratio",
            "0.1",
            "--edge-loss-weight",
            "1.0",
            "--flow-scale",
            "0.014",
            "--motion-mode",
            "jiggle",
            "--motion-strength",
            "0.014",
            "--experiment-label",
            "c34-general-flow-014-edge1-seed0",
            "--min-ocr-similarity",
            "0.84",
            "--min-motion-delta",
            "0.014",
        ],
    ),
    Experiment(
        label="c34-general-flow-014-edge1-seed1",
        notes="C34 robustness: repeat the C33 no-OCR winner with seed 1.",
        args=[
            *GENERAL_VISUAL_ARGS,
            "--seed",
            "1",
            "--edge-sample-ratio",
            "0.1",
            "--edge-loss-weight",
            "1.0",
            "--flow-scale",
            "0.014",
            "--motion-mode",
            "jiggle",
            "--motion-strength",
            "0.014",
            "--experiment-label",
            "c34-general-flow-014-edge1-seed1",
            "--min-ocr-similarity",
            "0.84",
            "--min-motion-delta",
            "0.014",
        ],
    ),
    Experiment(
        label="c34-general-flow-014-edge1-seed2",
        notes="C34 robustness: repeat the C33 no-OCR winner with seed 2.",
        args=[
            *GENERAL_VISUAL_ARGS,
            "--seed",
            "2",
            "--edge-sample-ratio",
            "0.1",
            "--edge-loss-weight",
            "1.0",
            "--flow-scale",
            "0.014",
            "--motion-mode",
            "jiggle",
            "--motion-strength",
            "0.014",
            "--experiment-label",
            "c34-general-flow-014-edge1-seed2",
            "--min-ocr-similarity",
            "0.84",
            "--min-motion-delta",
            "0.014",
        ],
    ),
    Experiment(
        label="c34-general-flow-014-edge1-seed3",
        notes="C34 robustness: repeat the C33 no-OCR winner with seed 3.",
        args=[
            *GENERAL_VISUAL_ARGS,
            "--seed",
            "3",
            "--edge-sample-ratio",
            "0.1",
            "--edge-loss-weight",
            "1.0",
            "--flow-scale",
            "0.014",
            "--motion-mode",
            "jiggle",
            "--motion-strength",
            "0.014",
            "--experiment-label",
            "c34-general-flow-014-edge1-seed3",
            "--min-ocr-similarity",
            "0.84",
            "--min-motion-delta",
            "0.014",
        ],
    ),
    Experiment(
        label="c34-general-flow-0141-edge1-seed0",
        notes="C34 cliff test: nudge pure no-OCR flow just above the C33 winner.",
        args=[
            *GENERAL_VISUAL_ARGS,
            "--seed",
            "0",
            "--edge-sample-ratio",
            "0.1",
            "--edge-loss-weight",
            "1.0",
            "--flow-scale",
            "0.0141",
            "--motion-mode",
            "jiggle",
            "--motion-strength",
            "0.0141",
            "--experiment-label",
            "c34-general-flow-0141-edge1-seed0",
            "--min-ocr-similarity",
            "0.82",
            "--min-motion-delta",
            "0.014",
        ],
    ),
    Experiment(
        label="c34-general-flow-01415-edge1-seed0",
        notes="C34 cliff test: bracket the narrow gap before the C33 0.01425 near-miss.",
        args=[
            *GENERAL_VISUAL_ARGS,
            "--seed",
            "0",
            "--edge-sample-ratio",
            "0.1",
            "--edge-loss-weight",
            "1.0",
            "--flow-scale",
            "0.01415",
            "--motion-mode",
            "jiggle",
            "--motion-strength",
            "0.01415",
            "--experiment-label",
            "c34-general-flow-01415-edge1-seed0",
            "--min-ocr-similarity",
            "0.80",
            "--min-motion-delta",
            "0.014",
        ],
    ),
    Experiment(
        label="c34-general-flow-0142-edge1-seed0",
        notes="C34 cliff test: test whether 0.0142 remains viable before the 0.01425 readability drop.",
        args=[
            *GENERAL_VISUAL_ARGS,
            "--seed",
            "0",
            "--edge-sample-ratio",
            "0.1",
            "--edge-loss-weight",
            "1.0",
            "--flow-scale",
            "0.0142",
            "--motion-mode",
            "jiggle",
            "--motion-strength",
            "0.0142",
            "--experiment-label",
            "c34-general-flow-0142-edge1-seed0",
            "--min-ocr-similarity",
            "0.78",
            "--min-motion-delta",
            "0.014",
        ],
    ),
    Experiment(
        label="c34-general-flow-014-edge09-seed0",
        notes="C34 edge bracket: test slightly lighter edge weighting at the C33 winner flow.",
        args=[
            *GENERAL_VISUAL_ARGS,
            "--seed",
            "0",
            "--edge-sample-ratio",
            "0.09",
            "--edge-loss-weight",
            "0.9",
            "--flow-scale",
            "0.014",
            "--motion-mode",
            "jiggle",
            "--motion-strength",
            "0.014",
            "--experiment-label",
            "c34-general-flow-014-edge09-seed0",
            "--min-ocr-similarity",
            "0.84",
            "--min-motion-delta",
            "0.014",
        ],
    ),
    Experiment(
        label="c34-general-responsive-014-edge1-seed0",
        notes="C34 responsive stress: apply the current winner flow to the no-OCR responsive-squeeze case.",
        args=[
            *GENERAL_VISUAL_ARGS,
            "--seed",
            "0",
            "--edge-sample-ratio",
            "0.1",
            "--edge-loss-weight",
            "1.0",
            "--flow-scale",
            "0.014",
            "--motion-mode",
            "responsive-squeeze",
            "--motion-strength",
            "0.014",
            "--video-viewport-mode",
            "zoom-pulse",
            "--viewport-zoom",
            "0.06",
            "--viewport-pan",
            "0.012",
            "--experiment-label",
            "c34-general-responsive-014-edge1-seed0",
            "--min-ocr-similarity",
            "0.80",
            "--min-motion-delta",
            "0.014",
        ],
    ),
    Experiment(
        label="c34-general-viewport-014-edge1-seed0",
        notes="C34 viewport stress: keep learned jiggle but add viewport zoom/pan to test query stability.",
        args=[
            *GENERAL_VISUAL_ARGS,
            "--seed",
            "0",
            "--edge-sample-ratio",
            "0.1",
            "--edge-loss-weight",
            "1.0",
            "--flow-scale",
            "0.014",
            "--motion-mode",
            "jiggle",
            "--motion-strength",
            "0.014",
            "--video-viewport-mode",
            "zoom-pulse",
            "--viewport-zoom",
            "0.06",
            "--viewport-pan",
            "0.012",
            "--experiment-label",
            "c34-general-viewport-014-edge1-seed0",
            "--min-ocr-similarity",
            "0.78",
            "--min-motion-delta",
            "0.014",
        ],
    ),
    Experiment(
        label="c33-general-flow-0135-edge075",
        notes="Scale-up pure neural canvas: bracket the C32 no-OCR winner with slightly lighter edge weighting.",
        args=[
            *GENERAL_VISUAL_ARGS,
            "--edge-sample-ratio",
            "0.075",
            "--edge-loss-weight",
            "0.75",
            "--flow-scale",
            "0.0135",
            "--motion-mode",
            "jiggle",
            "--motion-strength",
            "0.0135",
            "--experiment-label",
            "c33-general-flow-0135-edge075",
            "--min-ocr-similarity",
            "0.82",
            "--min-motion-delta",
            "0.013",
        ],
    ),
    Experiment(
        label="c33-general-flow-0135-edge15",
        notes="Scale-up pure neural canvas: bracket the C32 no-OCR winner with slightly stronger edge weighting.",
        args=[
            *GENERAL_VISUAL_ARGS,
            "--edge-sample-ratio",
            "0.15",
            "--edge-loss-weight",
            "1.5",
            "--flow-scale",
            "0.0135",
            "--motion-mode",
            "jiggle",
            "--motion-strength",
            "0.0135",
            "--experiment-label",
            "c33-general-flow-0135-edge15",
            "--min-ocr-similarity",
            "0.82",
            "--min-motion-delta",
            "0.013",
        ],
    ),
    Experiment(
        label="c33-general-flow-014-edge1",
        notes="Scale-up pure neural canvas: push no-OCR flow beyond the C32 winner at the best edge setting.",
        args=[
            *GENERAL_VISUAL_ARGS,
            "--edge-sample-ratio",
            "0.1",
            "--edge-loss-weight",
            "1.0",
            "--flow-scale",
            "0.014",
            "--motion-mode",
            "jiggle",
            "--motion-strength",
            "0.014",
            "--experiment-label",
            "c33-general-flow-014-edge1",
            "--min-ocr-similarity",
            "0.80",
            "--min-motion-delta",
            "0.014",
        ],
    ),
    Experiment(
        label="c33-general-flow-01425-edge1",
        notes="Scale-up pure neural canvas: find the no-OCR readability cliff above flow 0.014.",
        args=[
            *GENERAL_VISUAL_ARGS,
            "--edge-sample-ratio",
            "0.1",
            "--edge-loss-weight",
            "1.0",
            "--flow-scale",
            "0.01425",
            "--motion-mode",
            "jiggle",
            "--motion-strength",
            "0.01425",
            "--experiment-label",
            "c33-general-flow-01425-edge1",
            "--min-ocr-similarity",
            "0.78",
            "--min-motion-delta",
            "0.014",
        ],
    ),
    Experiment(
        label="c33-general-flow-0135-edge1-s6000",
        notes="Scale-up pure neural canvas: more optimization steps at the C32 no-OCR winner.",
        args=[
            "--steps",
            "6000",
            "--train-resolution",
            "1280x736",
            "--text-box-sample-ratio",
            "0",
            "--text-box-loss-weight",
            "0",
            "--text-box-padding",
            "0",
            "--text-box-min-conf",
            "55",
            "--edge-sample-ratio",
            "0.1",
            "--edge-loss-weight",
            "1.0",
            "--flow-scale",
            "0.0135",
            "--motion-mode",
            "jiggle",
            "--motion-strength",
            "0.0135",
            "--experiment-label",
            "c33-general-flow-0135-edge1-s6000",
            "--min-ocr-similarity",
            "0.84",
            "--min-motion-delta",
            "0.013",
        ],
    ),
    Experiment(
        label="c33-general-flow-0135-edge1-cap24h128",
        notes="Scale-up pure neural canvas: larger latent canvas/channel capacity on the current no-OCR winner.",
        args=[
            *GENERAL_VISUAL_ARGS,
            "--channels",
            "24",
            "--hidden",
            "128",
            "--edge-sample-ratio",
            "0.1",
            "--edge-loss-weight",
            "1.0",
            "--flow-scale",
            "0.0135",
            "--motion-mode",
            "jiggle",
            "--motion-strength",
            "0.0135",
            "--experiment-label",
            "c33-general-flow-0135-edge1-cap24h128",
            "--min-ocr-similarity",
            "0.84",
            "--min-motion-delta",
            "0.013",
        ],
    ),
    Experiment(
        label="c33-general-flow-014-edge05",
        notes="Scale-up pure neural canvas: push motion with lighter edge weighting after C32 edge05 improved quality.",
        args=[
            *GENERAL_VISUAL_ARGS,
            "--edge-sample-ratio",
            "0.05",
            "--edge-loss-weight",
            "0.5",
            "--flow-scale",
            "0.014",
            "--motion-mode",
            "jiggle",
            "--motion-strength",
            "0.014",
            "--experiment-label",
            "c33-general-flow-014-edge05",
            "--min-ocr-similarity",
            "0.80",
            "--min-motion-delta",
            "0.014",
        ],
    ),
    Experiment(
        label="c33-text-flow-01375-box8",
        notes="Scale-up bridge: split the gap between C31 box8 success and C32/C31 higher-flow failures.",
        args=[
            *BASE_ARGS,
            "--flow-scale",
            "0.01375",
            "--motion-mode",
            "jiggle",
            "--motion-strength",
            "0.01375",
            "--experiment-label",
            "c33-text-flow-01375-box8",
            "--min-ocr-similarity",
            "0.82",
            "--min-motion-delta",
            "0.013",
        ],
    ),
    Experiment(
        label="c33-text-flow-0135-box6",
        notes="Scale-up bridge: reduce OCR-box loss at the bridge winner flow to see if text boxes can be less dominant.",
        args=[
            "--steps",
            "4500",
            "--train-resolution",
            "1280x736",
            "--edge-sample-ratio",
            "0.1",
            "--edge-loss-weight",
            "1.0",
            "--text-box-sample-ratio",
            "0.45",
            "--text-box-loss-weight",
            "6.0",
            "--text-box-padding",
            "4",
            "--text-box-min-conf",
            "55",
            "--flow-scale",
            "0.0135",
            "--motion-mode",
            "jiggle",
            "--motion-strength",
            "0.0135",
            "--experiment-label",
            "c33-text-flow-0135-box6",
            "--min-ocr-similarity",
            "0.82",
            "--min-motion-delta",
            "0.013",
        ],
    ),
    Experiment(
        label="c33-general-responsive-012-edge1",
        notes="Scale-up pure neural canvas: no-OCR responsive-squeeze stress at a lower amplitude.",
        args=[
            *GENERAL_VISUAL_ARGS,
            "--edge-sample-ratio",
            "0.1",
            "--edge-loss-weight",
            "1.0",
            "--flow-scale",
            "0.012",
            "--motion-mode",
            "responsive-squeeze",
            "--motion-strength",
            "0.012",
            "--video-viewport-mode",
            "zoom-pulse",
            "--viewport-zoom",
            "0.06",
            "--viewport-pan",
            "0.012",
            "--experiment-label",
            "c33-general-responsive-012-edge1",
            "--min-ocr-similarity",
            "0.75",
            "--min-motion-delta",
            "0.012",
        ],
    ),
    Experiment(
        label="c32-general-flow-0125-edge05",
        notes="General neural-canvas refinement: lighter dense edge weighting around the C31 no-OCR winner.",
        args=[
            *GENERAL_VISUAL_ARGS,
            "--edge-sample-ratio",
            "0.05",
            "--edge-loss-weight",
            "0.5",
            "--flow-scale",
            "0.0125",
            "--motion-mode",
            "jiggle",
            "--motion-strength",
            "0.0125",
            "--experiment-label",
            "c32-general-flow-0125-edge05",
            "--min-ocr-similarity",
            "0.80",
            "--min-motion-delta",
            "0.012",
        ],
    ),
    Experiment(
        label="c32-general-flow-0135-edge1",
        notes="General neural-canvas refinement: push the best no-OCR edge setting to the bridge winner's motion level.",
        args=[
            *GENERAL_VISUAL_ARGS,
            "--edge-sample-ratio",
            "0.1",
            "--edge-loss-weight",
            "1.0",
            "--flow-scale",
            "0.0135",
            "--motion-mode",
            "jiggle",
            "--motion-strength",
            "0.0135",
            "--experiment-label",
            "c32-general-flow-0135-edge1",
            "--min-ocr-similarity",
            "0.78",
            "--min-motion-delta",
            "0.013",
        ],
    ),
    Experiment(
        label="c32-text-flow-0145-box8",
        notes="Text-aware learned-flow bridge: push beyond the C31 0.0135 bridge while avoiding render-time masks.",
        args=[
            *BASE_ARGS,
            "--flow-scale",
            "0.0145",
            "--motion-mode",
            "jiggle",
            "--motion-strength",
            "0.0145",
            "--experiment-label",
            "c32-text-flow-0145-box8",
            "--min-ocr-similarity",
            "0.78",
            "--min-motion-delta",
            "0.014",
        ],
    ),
    Experiment(
        label="c32-text-flow-0135-box12",
        notes="Text-aware learned-flow bridge: stronger OCR-box training signal at the current bridge winner flow.",
        args=[
            "--steps",
            "4500",
            "--train-resolution",
            "1280x736",
            "--edge-sample-ratio",
            "0.1",
            "--edge-loss-weight",
            "1.0",
            "--text-box-sample-ratio",
            "0.70",
            "--text-box-loss-weight",
            "12.0",
            "--text-box-padding",
            "4",
            "--text-box-min-conf",
            "55",
            "--flow-scale",
            "0.0135",
            "--motion-mode",
            "jiggle",
            "--motion-strength",
            "0.0135",
            "--experiment-label",
            "c32-text-flow-0135-box12",
            "--min-ocr-similarity",
            "0.82",
            "--min-motion-delta",
            "0.013",
        ],
    ),
    Experiment(
        label="c31-general-flow-0125-edge1",
        notes="General neural-canvas direction: no OCR boxes, baseline edge/glyph weighting at the C30 sweet-spot flow.",
        args=[
            *GENERAL_VISUAL_ARGS,
            "--edge-sample-ratio",
            "0.1",
            "--edge-loss-weight",
            "1.0",
            "--flow-scale",
            "0.0125",
            "--motion-mode",
            "jiggle",
            "--motion-strength",
            "0.0125",
            "--experiment-label",
            "c31-general-flow-0125-edge1",
            "--min-ocr-similarity",
            "0.78",
            "--min-motion-delta",
            "0.012",
        ],
    ),
    Experiment(
        label="c31-general-flow-0125-edge4",
        notes="General neural-canvas direction: no OCR boxes, stronger dense edge/glyph weighting at the C30 sweet-spot flow.",
        args=[
            *GENERAL_VISUAL_ARGS,
            "--edge-sample-ratio",
            "0.35",
            "--edge-loss-weight",
            "4.0",
            "--flow-scale",
            "0.0125",
            "--motion-mode",
            "jiggle",
            "--motion-strength",
            "0.0125",
            "--experiment-label",
            "c31-general-flow-0125-edge4",
            "--min-ocr-similarity",
            "0.78",
            "--min-motion-delta",
            "0.012",
        ],
    ),
    Experiment(
        label="c31-general-flow-010-edge4",
        notes="General neural-canvas direction: no OCR boxes, lower-flow recovery point with dense edge/glyph weighting.",
        args=[
            *GENERAL_VISUAL_ARGS,
            "--edge-sample-ratio",
            "0.35",
            "--edge-loss-weight",
            "4.0",
            "--flow-scale",
            "0.010",
            "--motion-mode",
            "jiggle",
            "--motion-strength",
            "0.010",
            "--experiment-label",
            "c31-general-flow-010-edge4",
            "--min-ocr-similarity",
            "0.80",
            "--min-motion-delta",
            "0.010",
        ],
    ),
    Experiment(
        label="c31-general-flow-0125-edge8",
        notes="General neural-canvas direction: no OCR boxes, very strong dense edge/glyph weighting to test over-sharpening versus readability.",
        args=[
            *GENERAL_VISUAL_ARGS,
            "--edge-sample-ratio",
            "0.55",
            "--edge-loss-weight",
            "8.0",
            "--flow-scale",
            "0.0125",
            "--motion-mode",
            "jiggle",
            "--motion-strength",
            "0.0125",
            "--experiment-label",
            "c31-general-flow-0125-edge8",
            "--min-ocr-similarity",
            "0.78",
            "--min-motion-delta",
            "0.012",
        ],
    ),
    Experiment(
        label="c31-text-flow-0135-box8",
        notes="Text-aware learned-flow bridge: OCR boxes affect training loss only, no output masks or layout anchors.",
        args=[
            *BASE_ARGS,
            "--flow-scale",
            "0.0135",
            "--motion-mode",
            "jiggle",
            "--motion-strength",
            "0.0135",
            "--experiment-label",
            "c31-text-flow-0135-box8",
            "--min-ocr-similarity",
            "0.80",
            "--min-motion-delta",
            "0.013",
        ],
    ),
    Experiment(
        label="c31-text-flow-014-box8",
        notes="Text-aware learned-flow bridge: push just past the C30 boundary without render-time masks.",
        args=[
            *BASE_ARGS,
            "--flow-scale",
            "0.014",
            "--motion-mode",
            "jiggle",
            "--motion-strength",
            "0.014",
            "--experiment-label",
            "c31-text-flow-014-box8",
            "--min-ocr-similarity",
            "0.78",
            "--min-motion-delta",
            "0.014",
        ],
    ),
    Experiment(
        label="c31-text-flow-0125-box12",
        notes="Text-aware learned-flow bridge: stronger OCR-box sampling/loss at the C30 sweet spot, still no output masks.",
        args=[
            "--steps",
            "4500",
            "--train-resolution",
            "1280x736",
            "--edge-sample-ratio",
            "0.1",
            "--edge-loss-weight",
            "1.0",
            "--text-box-sample-ratio",
            "0.70",
            "--text-box-loss-weight",
            "12.0",
            "--text-box-padding",
            "4",
            "--text-box-min-conf",
            "55",
            "--flow-scale",
            "0.0125",
            "--motion-mode",
            "jiggle",
            "--motion-strength",
            "0.0125",
            "--experiment-label",
            "c31-text-flow-0125-box12",
            "--min-ocr-similarity",
            "0.82",
            "--min-motion-delta",
            "0.012",
        ],
    ),
    Experiment(
        label="c31-alpha-layout-r0025-s004",
        notes="Shape-aware bridge: glyph alpha selection under gentle layout motion, testing a non-rectangle rescue path.",
        args=[
            *BASE_ARGS,
            "--flow-scale",
            "0",
            "--motion-mode",
            "static",
            "--motion-strength",
            "0",
            "--video-layout-mode",
            "element-frame-scale",
            "--layout-transform-strength",
            "0.04",
            "--layout-transform-pan",
            "0.008",
            "--element-anchor-mode",
            "line",
            "--element-render-mode",
            "batched",
            "--element-scale-ratio",
            "0.025",
            "--element-anchor-padding",
            "4",
            "--element-mask-mode",
            "text-alpha",
            "--experiment-label",
            "c31-alpha-layout-r0025-s004",
            "--min-ocr-similarity",
            "0.60",
            "--min-motion-delta",
            "0.015",
        ],
    ),
    Experiment(
        label="c30-gentle-flow-0125",
        notes="Pleasant-motion boundary between the C29 0.010 pass and 0.020 quality drop.",
        args=[
            *BASE_ARGS,
            "--flow-scale",
            "0.0125",
            "--motion-mode",
            "jiggle",
            "--motion-strength",
            "0.0125",
            "--experiment-label",
            "c30-gentle-flow-0125",
            "--min-ocr-similarity",
            "0.80",
            "--min-motion-delta",
            "0.012",
        ],
    ),
    Experiment(
        label="c30-gentle-flow-015",
        notes="Pleasant-motion boundary probe near the likely readability cliff.",
        args=[
            *BASE_ARGS,
            "--flow-scale",
            "0.015",
            "--motion-mode",
            "jiggle",
            "--motion-strength",
            "0.015",
            "--experiment-label",
            "c30-gentle-flow-015",
            "--min-ocr-similarity",
            "0.78",
            "--min-motion-delta",
            "0.015",
        ],
    ),
    Experiment(
        label="c30-product-layout-r0025-s008",
        notes="Pleasant layout-motion with best line ratio and moderate layout strength.",
        args=[
            *BASE_ARGS,
            "--flow-scale",
            "0",
            "--motion-mode",
            "static",
            "--motion-strength",
            "0",
            "--video-layout-mode",
            "element-frame-scale",
            "--layout-transform-strength",
            "0.08",
            "--layout-transform-pan",
            "0.015",
            "--element-anchor-mode",
            "line",
            "--element-render-mode",
            "batched",
            "--element-scale-ratio",
            "0.025",
            "--element-anchor-padding",
            "4",
            "--element-mask-mode",
            "rectangle",
            "--experiment-label",
            "c30-product-layout-r0025-s008",
            "--min-ocr-similarity",
            "0.75",
            "--min-motion-delta",
            "0.025",
        ],
    ),
    Experiment(
        label="c30-line-batched-r0025-strong",
        notes="Batched control for the current best strong-stress line ratio.",
        args=[
            *BASE_ARGS,
            "--flow-scale",
            "0",
            "--motion-mode",
            "static",
            "--motion-strength",
            "0",
            "--video-layout-mode",
            "element-frame-scale",
            "--layout-transform-strength",
            "0.18",
            "--layout-transform-pan",
            "0.035",
            "--element-anchor-mode",
            "line",
            "--element-render-mode",
            "batched",
            "--element-scale-ratio",
            "0.025",
            "--element-anchor-padding",
            "4",
            "--element-mask-mode",
            "rectangle",
            "--experiment-label",
            "c30-line-batched-r0025-strong",
            "--min-ocr-similarity",
            "0.65",
        ],
    ),
    Experiment(
        label="c29-gentle-flow-010",
        notes="Pleasant-motion ladder: double the C2.1 flow while trying to preserve text.",
        args=[
            *BASE_ARGS,
            "--flow-scale",
            "0.010",
            "--motion-mode",
            "jiggle",
            "--motion-strength",
            "0.010",
            "--experiment-label",
            "c29-gentle-flow-010",
            "--min-ocr-similarity",
            "0.80",
            "--min-motion-delta",
            "0.010",
        ],
    ),
    Experiment(
        label="c29-gentle-flow-020",
        notes="Pleasant-motion ladder: stronger learned motion, still below resize/reflow stress.",
        args=[
            *BASE_ARGS,
            "--flow-scale",
            "0.020",
            "--motion-mode",
            "jiggle",
            "--motion-strength",
            "0.020",
            "--experiment-label",
            "c29-gentle-flow-020",
            "--min-ocr-similarity",
            "0.75",
            "--min-motion-delta",
            "0.020",
        ],
    ),
    Experiment(
        label="c29-product-layout-r0025",
        notes="Pleasant layout-motion baseline using the best strong-stress line ratio at low layout strength.",
        args=[
            *BASE_ARGS,
            "--flow-scale",
            "0",
            "--motion-mode",
            "static",
            "--motion-strength",
            "0",
            "--video-layout-mode",
            "element-frame-scale",
            "--layout-transform-strength",
            "0.04",
            "--layout-transform-pan",
            "0.008",
            "--element-anchor-mode",
            "line",
            "--element-render-mode",
            "batched",
            "--element-scale-ratio",
            "0.025",
            "--element-anchor-padding",
            "4",
            "--element-mask-mode",
            "rectangle",
            "--experiment-label",
            "c29-product-layout-r0025",
            "--min-ocr-similarity",
            "0.75",
            "--min-motion-delta",
            "0.015",
        ],
    ),
    Experiment(
        label="c28-word-batched-r010",
        notes="Human-positive word anchors with batched patch rendering to recover latency.",
        args=[
            *BASE_ARGS,
            "--flow-scale",
            "0",
            "--motion-mode",
            "static",
            "--motion-strength",
            "0",
            "--video-layout-mode",
            "element-frame-scale",
            "--layout-transform-strength",
            "0.18",
            "--layout-transform-pan",
            "0.035",
            "--element-anchor-mode",
            "word",
            "--element-render-mode",
            "batched",
            "--element-scale-ratio",
            "0.10",
            "--element-anchor-padding",
            "3",
            "--element-mask-mode",
            "rectangle",
            "--experiment-label",
            "c28-word-batched-r010",
            "--min-ocr-similarity",
            "0.35",
        ],
    ),
    Experiment(
        label="c28-word-batched-moderate-r010",
        notes="Human-positive word anchors batched under moderate stress.",
        args=[
            *BASE_ARGS,
            "--flow-scale",
            "0",
            "--motion-mode",
            "static",
            "--motion-strength",
            "0",
            "--video-layout-mode",
            "element-frame-scale",
            "--layout-transform-strength",
            "0.08",
            "--layout-transform-pan",
            "0.015",
            "--element-anchor-mode",
            "word",
            "--element-render-mode",
            "batched",
            "--element-scale-ratio",
            "0.10",
            "--element-anchor-padding",
            "3",
            "--element-mask-mode",
            "rectangle",
            "--experiment-label",
            "c28-word-batched-moderate-r010",
            "--min-ocr-similarity",
            "0.50",
        ],
    ),
    Experiment(
        label="c28-line-batched-r005",
        notes="Batched line-anchor control should match C2.6 quality while confirming batching does not change pixels.",
        args=[
            *BASE_ARGS,
            "--flow-scale",
            "0",
            "--motion-mode",
            "static",
            "--motion-strength",
            "0",
            "--video-layout-mode",
            "element-frame-scale",
            "--layout-transform-strength",
            "0.18",
            "--layout-transform-pan",
            "0.035",
            "--element-anchor-mode",
            "line",
            "--element-render-mode",
            "batched",
            "--element-scale-ratio",
            "0.05",
            "--element-anchor-padding",
            "4",
            "--element-mask-mode",
            "rectangle",
            "--experiment-label",
            "c28-line-batched-r005",
            "--min-ocr-similarity",
            "0.35",
        ],
    ),
    Experiment(
        label="c27-line-rect-r0025",
        notes="Line anchor ratio sweep below current best 0.05.",
        args=[
            *BASE_ARGS,
            "--flow-scale",
            "0",
            "--motion-mode",
            "static",
            "--motion-strength",
            "0",
            "--video-layout-mode",
            "element-frame-scale",
            "--layout-transform-strength",
            "0.18",
            "--layout-transform-pan",
            "0.035",
            "--element-anchor-mode",
            "line",
            "--element-scale-ratio",
            "0.025",
            "--element-anchor-padding",
            "4",
            "--element-mask-mode",
            "rectangle",
            "--experiment-label",
            "c27-line-rect-r0025",
            "--min-ocr-similarity",
            "0.35",
        ],
    ),
    Experiment(
        label="c27-line-rect-r0075",
        notes="Line anchor ratio sweep above current best 0.05 but below previous 0.10.",
        args=[
            *BASE_ARGS,
            "--flow-scale",
            "0",
            "--motion-mode",
            "static",
            "--motion-strength",
            "0",
            "--video-layout-mode",
            "element-frame-scale",
            "--layout-transform-strength",
            "0.18",
            "--layout-transform-pan",
            "0.035",
            "--element-anchor-mode",
            "line",
            "--element-scale-ratio",
            "0.075",
            "--element-anchor-padding",
            "4",
            "--element-mask-mode",
            "rectangle",
            "--experiment-label",
            "c27-line-rect-r0075",
            "--min-ocr-similarity",
            "0.35",
        ],
    ),
    Experiment(
        label="c27-line-rect-r005-pad2",
        notes="Current best ratio with tighter support boxes to reduce unrelated illustration capture.",
        args=[
            *BASE_ARGS,
            "--flow-scale",
            "0",
            "--motion-mode",
            "static",
            "--motion-strength",
            "0",
            "--video-layout-mode",
            "element-frame-scale",
            "--layout-transform-strength",
            "0.18",
            "--layout-transform-pan",
            "0.035",
            "--element-anchor-mode",
            "line",
            "--element-scale-ratio",
            "0.05",
            "--element-anchor-padding",
            "2",
            "--element-mask-mode",
            "rectangle",
            "--experiment-label",
            "c27-line-rect-r005-pad2",
            "--min-ocr-similarity",
            "0.35",
        ],
    ),
    Experiment(
        label="c27-line-rect-r005-pad6",
        notes="Current best ratio with wider support boxes to check whether extra local context improves OCR.",
        args=[
            *BASE_ARGS,
            "--flow-scale",
            "0",
            "--motion-mode",
            "static",
            "--motion-strength",
            "0",
            "--video-layout-mode",
            "element-frame-scale",
            "--layout-transform-strength",
            "0.18",
            "--layout-transform-pan",
            "0.035",
            "--element-anchor-mode",
            "line",
            "--element-scale-ratio",
            "0.05",
            "--element-anchor-padding",
            "6",
            "--element-mask-mode",
            "rectangle",
            "--experiment-label",
            "c27-line-rect-r005-pad6",
            "--min-ocr-similarity",
            "0.35",
        ],
    ),
    Experiment(
        label="c27-responsive-018",
        notes="Responsive-squeeze boundary between strong 0.16 pass and xstrong 0.22 fail.",
        args=[
            *BASE_ARGS,
            "--flow-scale",
            "0.18",
            "--motion-mode",
            "responsive-squeeze",
            "--motion-strength",
            "0.18",
            "--video-viewport-mode",
            "zoom-pulse",
            "--viewport-zoom",
            "0.14",
            "--viewport-pan",
            "0.030",
            "--experiment-label",
            "c27-responsive-018",
            "--min-ocr-similarity",
            "0.25",
        ],
    ),
    Experiment(
        label="c26-word-rect-r010",
        notes="Word-level support rectangles: preserve text background while avoiding large line boxes that can catch illustration pixels.",
        args=[
            *BASE_ARGS,
            "--flow-scale",
            "0",
            "--motion-mode",
            "static",
            "--motion-strength",
            "0",
            "--video-layout-mode",
            "element-frame-scale",
            "--layout-transform-strength",
            "0.18",
            "--layout-transform-pan",
            "0.035",
            "--element-anchor-mode",
            "word",
            "--element-scale-ratio",
            "0.10",
            "--element-anchor-padding",
            "3",
            "--element-mask-mode",
            "rectangle",
            "--experiment-label",
            "c26-word-rect-r010",
            "--min-ocr-similarity",
            "0.35",
        ],
    ),
    Experiment(
        label="c26-word-rect-moderate-r010",
        notes="Moderate stress word-level support rectangle control.",
        args=[
            *BASE_ARGS,
            "--flow-scale",
            "0",
            "--motion-mode",
            "static",
            "--motion-strength",
            "0",
            "--video-layout-mode",
            "element-frame-scale",
            "--layout-transform-strength",
            "0.08",
            "--layout-transform-pan",
            "0.015",
            "--element-anchor-mode",
            "word",
            "--element-scale-ratio",
            "0.10",
            "--element-anchor-padding",
            "3",
            "--element-mask-mode",
            "rectangle",
            "--experiment-label",
            "c26-word-rect-moderate-r010",
            "--min-ocr-similarity",
            "0.50",
        ],
    ),
    Experiment(
        label="c26-line-rect-r005",
        notes="Line anchor scale-ratio refinement below the current best 0.10.",
        args=[
            *BASE_ARGS,
            "--flow-scale",
            "0",
            "--motion-mode",
            "static",
            "--motion-strength",
            "0",
            "--video-layout-mode",
            "element-frame-scale",
            "--layout-transform-strength",
            "0.18",
            "--layout-transform-pan",
            "0.035",
            "--element-anchor-mode",
            "line",
            "--element-scale-ratio",
            "0.05",
            "--element-anchor-padding",
            "4",
            "--element-mask-mode",
            "rectangle",
            "--experiment-label",
            "c26-line-rect-r005",
            "--min-ocr-similarity",
            "0.35",
        ],
    ),
    Experiment(
        label="c26-responsive-xstrong",
        notes="Very strong responsive-squeeze boundary after the strong run still passed.",
        args=[
            *BASE_ARGS,
            "--flow-scale",
            "0.22",
            "--motion-mode",
            "responsive-squeeze",
            "--motion-strength",
            "0.22",
            "--video-viewport-mode",
            "zoom-pulse",
            "--viewport-zoom",
            "0.16",
            "--viewport-pan",
            "0.035",
            "--experiment-label",
            "c26-responsive-xstrong",
            "--min-ocr-similarity",
            "0.25",
        ],
    ),
    Experiment(
        label="c25-alpha-r000",
        notes="Relaunch text-alpha strong stress ratio 0.00 after run-id collision fix.",
        args=[
            *BASE_ARGS,
            "--flow-scale",
            "0",
            "--motion-mode",
            "static",
            "--motion-strength",
            "0",
            "--video-layout-mode",
            "element-frame-scale",
            "--layout-transform-strength",
            "0.18",
            "--layout-transform-pan",
            "0.035",
            "--element-scale-ratio",
            "0.00",
            "--element-anchor-padding",
            "4",
            "--element-mask-mode",
            "text-alpha",
            "--experiment-label",
            "c25-alpha-r000",
            "--min-ocr-similarity",
            "0.35",
        ],
    ),
    Experiment(
        label="c25-alpha-r025",
        notes="Relaunch text-alpha strong stress ratio 0.25 after run-id collision fix.",
        args=[
            *BASE_ARGS,
            "--flow-scale",
            "0",
            "--motion-mode",
            "static",
            "--motion-strength",
            "0",
            "--video-layout-mode",
            "element-frame-scale",
            "--layout-transform-strength",
            "0.18",
            "--layout-transform-pan",
            "0.035",
            "--element-scale-ratio",
            "0.25",
            "--element-anchor-padding",
            "4",
            "--element-mask-mode",
            "text-alpha",
            "--experiment-label",
            "c25-alpha-r025",
            "--min-ocr-similarity",
            "0.35",
        ],
    ),
    Experiment(
        label="c25-alpha-moderate-r010",
        notes="Check whether text-alpha only fails under strong stress or also moderate stress.",
        args=[
            *BASE_ARGS,
            "--flow-scale",
            "0",
            "--motion-mode",
            "static",
            "--motion-strength",
            "0",
            "--video-layout-mode",
            "element-frame-scale",
            "--layout-transform-strength",
            "0.08",
            "--layout-transform-pan",
            "0.015",
            "--element-scale-ratio",
            "0.10",
            "--element-anchor-padding",
            "4",
            "--element-mask-mode",
            "text-alpha",
            "--experiment-label",
            "c25-alpha-moderate-r010",
            "--min-ocr-similarity",
            "0.50",
        ],
    ),
    Experiment(
        label="c25-rectangle-r010",
        notes="Rectangle anchor ratio 0.10 control to separate alpha-mask failure from scale-ratio behavior.",
        args=[
            *BASE_ARGS,
            "--flow-scale",
            "0",
            "--motion-mode",
            "static",
            "--motion-strength",
            "0",
            "--video-layout-mode",
            "element-frame-scale",
            "--layout-transform-strength",
            "0.18",
            "--layout-transform-pan",
            "0.035",
            "--element-scale-ratio",
            "0.10",
            "--element-anchor-padding",
            "4",
            "--element-mask-mode",
            "rectangle",
            "--experiment-label",
            "c25-rectangle-r010",
            "--min-ocr-similarity",
            "0.35",
        ],
    ),
    Experiment(
        label="c25-responsive-strong",
        notes="Stronger responsive-squeeze boundary after the first responsive-squeeze pass.",
        args=[
            *BASE_ARGS,
            "--flow-scale",
            "0.16",
            "--motion-mode",
            "responsive-squeeze",
            "--motion-strength",
            "0.16",
            "--video-viewport-mode",
            "zoom-pulse",
            "--viewport-zoom",
            "0.12",
            "--viewport-pan",
            "0.025",
            "--experiment-label",
            "c25-responsive-strong",
            "--min-ocr-similarity",
            "0.25",
        ],
    ),
]


def log(message: str) -> None:
    stamp = datetime.now(timezone.utc).isoformat(timespec="seconds")
    LOOP_LOG.parent.mkdir(parents=True, exist_ok=True)
    with LOOP_LOG.open("a", encoding="utf-8") as handle:
        handle.write(f"[{stamp}] {message}\n")
    print(message, flush=True)


def tmux_sessions() -> set[str]:
    result = subprocess.run(["tmux", "list-sessions", "-F", "#{session_name}"], text=True, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
    if result.returncode != 0:
        return set()
    return {line.strip() for line in result.stdout.splitlines() if line.strip()}


def log_done(path: Path) -> bool:
    if not path.exists():
        return False
    text = path.read_text(encoding="utf-8", errors="replace")
    if "FileExistsError" in text:
        return False
    return "DONE " in text or "Traceback" in text or "Invalid value" in text


def launch(exp: Experiment) -> None:
    command = " ".join(
        [
            "cd /Users/dennisonbertram/Develop/flipbook-research",
            "&&",
            f"FLIPBOOK_COMMIT={COMMIT}",
            "modal",
            "run",
            "scripts/track_c/modal_canvas_c2_lite.py",
            *exp.args,
            ">",
            str(exp.log_path),
            "2>&1",
        ]
    )
    subprocess.run(["tmux", "new-session", "-d", "-s", exp.session, command], check=True)
    log(f"launched {exp.label}: {exp.notes}")


def evaluate() -> None:
    result = subprocess.run(
        ["python3", "scripts/track_c/evaluate_run.py"],
        cwd=ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    for line in result.stdout.splitlines():
        log(f"eval {line}")


def summarize() -> None:
    state = {
        "updated_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "active_sessions": sorted(tmux_sessions()),
        "experiments": [
            {
                "label": exp.label,
                "session": exp.session,
                "log": str(exp.log_path.relative_to(ROOT)),
                "done": log_done(exp.log_path),
                "notes": exp.notes,
            }
            for exp in EXPERIMENTS
        ],
    }
    STATE_PATH.write_text(json.dumps(state, indent=2) + "\n", encoding="utf-8")

    lines = [
        "# Track C Autoresearch Status",
        "",
        f"Updated UTC: `{state['updated_utc']}`",
        "",
        "## Active Sessions",
        "",
    ]
    if state["active_sessions"]:
        lines.extend(f"- `{name}`" for name in state["active_sessions"])
    else:
        lines.append("- none")
    lines.extend(["", "## Queue", ""])
    for item in state["experiments"]:
        status = "done" if item["done"] else "pending/running"
        lines.append(f"- `{item['label']}`: {status} - {item['notes']}")
    STATUS_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    log("autoresearch loop started")
    while True:
        sessions = tmux_sessions()
        active_owned = {
            name
            for name in sessions
            if name.startswith("track-c-") and name not in {"track-c-autoresearch", "track-c-github-sync"}
        }
        for exp in EXPERIMENTS:
            if len(active_owned) >= MAX_PARALLEL:
                break
            if exp.session in sessions or log_done(exp.log_path):
                continue
            launch(exp)
            active_owned.add(exp.session)
        evaluate()
        summarize()
        time.sleep(300)


if __name__ == "__main__":
    main()
